sudo: false
dist: trusty
language: ruby
cache:
  yarn: true
  bundler: true
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - yarn install
script:
  - yarn run lint
  - bundle exec rubocop
  - bundle exec rake
